package com.sigepro.web.model.dto;

import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.commons.lang3.text.WordUtils;

// Generated 15-ago-2013 0:47:31 by Hibernate Tools 3.4.0.CR1


/**
 * Incidencia generated by hbm2java
 */
public class IncidenciaDTO implements java.io.Serializable {

	private Long idincidencia;
	private Integer idtipoincidencia;
	private String descripcionTipoIncidencia;
	private Integer idestadoinc;
	private String descripcionEstadoIncidencia;
	private int idcliente;
	private String clienteNombre;
	private String fechaInicio;
	private String fechaCierre;
	private String fechaUltMod;
	private String descripcion;
	private String titulo;
	private Long idvisita;

	public IncidenciaDTO() {
	}
	
	

	public IncidenciaDTO(Long idincidencia, Integer idtipoincidencia,
			String descripcionTipoIncidencia, Integer idestadoinc,
			String descripcionEstadoIncidencia, int idcliente,
			String clienteNombre, String clienteApellido, Date fechaInicio, Date fechaCierre,
			String descripcion, String titulo) {
		SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");		
		this.idincidencia = idincidencia;
		this.idtipoincidencia = idtipoincidencia;
		this.descripcionTipoIncidencia = descripcionTipoIncidencia;
		this.idestadoinc = idestadoinc;
		this.descripcionEstadoIncidencia = descripcionEstadoIncidencia;
		this.idcliente = idcliente;
		this.clienteNombre = WordUtils.capitalize(clienteNombre)+" "+WordUtils.capitalize(clienteApellido);
		this.fechaInicio = dateFormat.format(fechaInicio);
		if (fechaCierre!=null){
		this.fechaCierre = dateFormat.format(fechaCierre);
		}
//		this.fechaUltMod = fechaUltMod;
		this.descripcion = descripcion;
		this.titulo = titulo;
	}



	public Long getIdincidencia() {
		return idincidencia;
	}

	public void setIdincidencia(Long idincidencia) {
		this.idincidencia = idincidencia;
	}

	public Integer getIdtipoincidencia() {
		return idtipoincidencia;
	}

	public void setIdtipoincidencia(Integer idtipoincidencia) {
		this.idtipoincidencia = idtipoincidencia;
	}

	public String getDescripcionTipoIncidencia() {
		return descripcionTipoIncidencia;
	}

	public void setDescripcionTipoIncidencia(String descripcionTipoIncidencia) {
		this.descripcionTipoIncidencia = descripcionTipoIncidencia;
	}

	public Integer getIdestadoinc() {
		return idestadoinc;
	}

	public void setIdestadoinc(Integer idestadoinc) {
		this.idestadoinc = idestadoinc;
	}

	public String getDescripcionEstadoIncidencia() {
		return descripcionEstadoIncidencia;
	}

	public void setDescripcionEstadoIncidencia(String descripcionEstadoIncidencia) {
		this.descripcionEstadoIncidencia = descripcionEstadoIncidencia;
	}

	public int getIdcliente() {
		return idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}


	public String getClienteNombre() {
		return clienteNombre;
	}

	public void setClienteNombre(String clienteNombre) {
		this.clienteNombre = clienteNombre;
	}

	public String getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaCierre() {
		return fechaCierre;
	}

	public void setFechaCierre(String fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public String getFechaUltMod() {
		return fechaUltMod;
	}

	public void setFechaUltMod(String fechaUltMod) {
		this.fechaUltMod = fechaUltMod;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Long getIdvisita() {
		return idvisita;
	}

	public void setIdvisita(Long idvisita) {
		this.idvisita = idvisita;
	}


	

	
}
