package com.sigepro.web.model.pojo;

// Generated 30-jun-2013 19:41:32 by Hibernate Tools 3.4.0.CR1

/**
 * Abono generated by hbm2java
 */
public class Abono implements java.io.Serializable {

	private Integer idabono;
	private String nombre;
	private String descripcion;
	private Double minbajada;
	private Double maxbajada;
	private Double minsubida;
	private Double maxsubida;
	private Double precio;
	private Integer multiTipo;

	public Abono() {
	}

	public Abono(int idabono) {
		this.idabono = idabono;
	}

	public Abono(Integer idabono, String nombre, String descripcion,
			Double minbajada, Double maxbajada, Double minsubida,
			Double maxsubida, Double precio, Integer multiTipo) {
		this.idabono = idabono;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.minbajada = minbajada;
		this.maxbajada = maxbajada;
		this.minsubida = minsubida;
		this.maxsubida = maxsubida;
		this.precio = precio;
		this.multiTipo = multiTipo;
	}

	public Integer getIdabono() {
		return this.idabono;
	}

	public void setIdabono(Integer idabono) {
		this.idabono = idabono;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getMinbajada() {
		return this.minbajada;
	}

	public void setMinbajada(Double minbajada) {
		this.minbajada = minbajada;
	}

	public Double getMaxbajada() {
		return this.maxbajada;
	}

	public void setMaxbajada(Double maxbajada) {
		this.maxbajada = maxbajada;
	}

	public Double getMinsubida() {
		return this.minsubida;
	}

	public void setMinsubida(Double minsubida) {
		this.minsubida = minsubida;
	}

	public Double getMaxsubida() {
		return this.maxsubida;
	}

	public void setMaxsubida(Double maxsubida) {
		this.maxsubida = maxsubida;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	public Integer getMultiTipo() {
		return this.multiTipo;
	}

	public void setMultiTipo(Integer multiTipo) {
		this.multiTipo = multiTipo;
	}

}
