package com.sigepro.web.model.pojo;

// Generated 02-jul-2013 2:27:05 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * CatDnitipo generated by hbm2java
 */
public class CatDnitipo implements java.io.Serializable {

	private Integer iddnitipo;
	private String descripcion;
	@JsonIgnore
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public CatDnitipo() {
	}

	public CatDnitipo(int iddnitipo) {
		this.iddnitipo = iddnitipo;
	}

	public CatDnitipo(Integer iddnitipo, String descripcion, Set<Cliente> clientes) {
		this.iddnitipo = iddnitipo;
		this.descripcion = descripcion;
		this.clientes = clientes;
	}

	public Integer getIddnitipo() {
		return this.iddnitipo;
	}

	public void setIddnitipo(Integer iddnitipo) {
		this.iddnitipo = iddnitipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
