package com.sigepro.web.model.pojo;

// Generated 30-jun-2013 19:41:32 by Hibernate Tools 3.4.0.CR1

/**
 * ClienteAbonoId generated by hbm2java
 */
public class ClienteAbonoId implements java.io.Serializable {

	private int idcliente;
	private int idabono;

	public ClienteAbonoId() {
	}

	public ClienteAbonoId(int idcliente, int idabono) {
		this.idcliente = idcliente;
		this.idabono = idabono;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public int getIdabono() {
		return this.idabono;
	}

	public void setIdabono(int idabono) {
		this.idabono = idabono;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteAbonoId))
			return false;
		ClienteAbonoId castOther = (ClienteAbonoId) other;

		return (this.getIdcliente() == castOther.getIdcliente())
				&& (this.getIdabono() == castOther.getIdabono());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcliente();
		result = 37 * result + this.getIdabono();
		return result;
	}

}
