package com.sigepro.web.model.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated 30-jun-2013 19:41:32 by Hibernate Tools 3.4.0.CR1

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idcliente;
	private Localidad localidad;
	private EstadoCli estadoCli;
	private CatDnitipo catDnitipo;
	private String nombre;
	private String apellido;
	private String direccion;
	private String email;
	private String telefono;
	private String notas;
	private String ccNro;
	private Integer puntuacion;
	private Date fechaAgregado;
	private String cuit;
	private String telefono2;
	private String telefono3;
	private String numerocli;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public Cliente() {
	}

	public Cliente(int idcliente, String nombre) {
		this.idcliente = idcliente;
		this.nombre = nombre;
	}

	public Cliente(int idcliente, Localidad localidad, EstadoCli estadoCli,
			String nombre, String apellido, String direccion, String email,
			String telefono, String notas, String ccNro, Integer puntuacion,
			Date fechaAgregado, String cuit, String telefono2,
			String telefono3) {
		this.idcliente = idcliente;
		this.localidad = localidad;
		this.estadoCli = estadoCli;
		this.nombre = nombre;
		this.apellido = apellido;
		this.direccion = direccion;
		this.email = email;
		this.telefono = telefono;
		this.notas = notas;
		this.ccNro = ccNro;
		this.puntuacion = puntuacion;
		this.fechaAgregado = fechaAgregado;
		this.cuit = cuit;
		this.telefono2 = telefono2;
		this.telefono3 = telefono3;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public EstadoCli getEstadoCli() {
		return this.estadoCli;
	}

	public void setEstadoCli(EstadoCli estadoCli) {
		this.estadoCli = estadoCli;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public String getCcNro() {
		return this.ccNro;
	}

	public void setCcNro(String ccNro) {
		this.ccNro = ccNro;
	}

	public Integer getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(Integer puntuacion) {
		this.puntuacion = puntuacion;
	}

	public Date getFechaAgregado() {
		return this.fechaAgregado;
	}

	public void setFechaAgregado(Date fechaAgregado) {
		this.fechaAgregado = fechaAgregado;
	}

	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getTelefono3() {
		return this.telefono3;
	}

	public void setTelefono3(String telefono3) {
		this.telefono3 = telefono3;
	}

	public CatDnitipo getCatDnitipo() {
		return catDnitipo;
	}

	public void setCatDnitipo(CatDnitipo catDnitipo) {
		this.catDnitipo = catDnitipo;
	}

	public String getNumerocli() {
		return numerocli;
	}

	public void setNumerocli(String numerocli) {
		this.numerocli = numerocli;
	}

	public Set<Incidencia> getIncidencias() {
		return incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}
	
	
	

}
