package com.sigepro.web.model.pojo;

// Generated 02/06/2013 23:23:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCli generated by hbm2java
 */
public class EstadoCli implements java.io.Serializable {

	private Integer idestadocli;
	private String descripcion;
	private String notas;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public EstadoCli() {
	}

	public EstadoCli(Integer idestadocli, String descripcion) {
		this.idestadocli = idestadocli;
		this.descripcion = descripcion;
	}

	public EstadoCli(Integer idestadocli, String descripcion, String notas,
			Set<Cliente> clientes) {
		this.idestadocli = idestadocli;
		this.descripcion = descripcion;
		this.notas = notas;
		this.clientes = clientes;
	}

	public Integer getIdestadocli() {
		return this.idestadocli;
	}

	public void setIdestadocli(Integer idestadocli) {
		this.idestadocli = idestadocli;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
