package com.sigepro.web.model.pojo;

// Generated 15-ago-2013 0:47:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoInc generated by hbm2java
 */
public class EstadoInc implements java.io.Serializable {

	private Integer idestadoinc;
	private String descripcion;
	private String notas;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public EstadoInc() {
	}

	public EstadoInc(Integer idestadoinc) {
		this.idestadoinc = idestadoinc;
	}

	public EstadoInc(Integer idestadoinc, String descripcion, String notas,
			Set<Incidencia> incidencias) {
		this.idestadoinc = idestadoinc;
		this.descripcion = descripcion;
		this.notas = notas;
		this.incidencias = incidencias;
	}

	public Integer getIdestadoinc() {
		return this.idestadoinc;
	}

	public void setIdestadoinc(Integer idestadoinc) {
		this.idestadoinc = idestadoinc;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public Set<Incidencia> getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}

}
