package com.sigepro.web.model.pojo;

// Generated 15-ago-2013 0:47:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * EstadoVis generated by hbm2java
 */
public class EstadoVis implements java.io.Serializable {

	private Integer idestadovis;
	private String descripcion;
	private String notas;
	@JsonIgnore
	private Set<Visita> visitas = new HashSet<Visita>(0);

	public EstadoVis() {
	}
	
	public EstadoVis(Integer idestadovis, String descripcion, String notas,
			Set<Visita> visitas) {
		super();
		this.idestadovis = idestadovis;
		this.descripcion = descripcion;
		this.notas = notas;
		this.visitas = visitas;
	}

	public Integer getIdestadovis() {
		return idestadovis;
	}

	public void setIdestadovis(Integer idestadovis) {
		this.idestadovis = idestadovis;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNotas() {
		return notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public Set<Visita> getVisitas() {
		return visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}


}
