package com.sigepro.web.model.pojo;

// Generated 03-sep-2013 1:05:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HistoriaInc generated by hbm2java
 */
public class HistoriaInc implements java.io.Serializable {

	private HistoriaIncId id;
	private Date timestamp;
	private Visita visita;
	private EstadoInc estadoInc;
	private Incidencia incidencia;
	private Cliente cliente;
	private String descripcion;
	private Integer userid;

	public HistoriaInc() {
	}

	public HistoriaInc(HistoriaIncId id, Incidencia incidencia, Cliente cliente) {
		this.id = id;
		this.incidencia = incidencia;
		this.cliente = cliente;
	}

	public HistoriaInc(HistoriaIncId id, Visita visita, EstadoInc estadoInc,
			Incidencia incidencia, Cliente cliente, String descripcion,
			Integer userid) {
		this.id = id;
		this.visita = visita;
		this.estadoInc = estadoInc;
		this.incidencia = incidencia;
		this.cliente = cliente;
		this.descripcion = descripcion;
		this.userid = userid;
	}

	public HistoriaIncId getId() {
		return this.id;
	}

	public void setId(HistoriaIncId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Visita getVisita() {
		return this.visita;
	}

	public void setVisita(Visita visita) {
		this.visita = visita;
	}

	public EstadoInc getEstadoInc() {
		return this.estadoInc;
	}

	public void setEstadoInc(EstadoInc estadoInc) {
		this.estadoInc = estadoInc;
	}

	public Incidencia getIncidencia() {
		return this.incidencia;
	}

	public void setIncidencia(Incidencia incidencia) {
		this.incidencia = incidencia;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

}
