package com.sigepro.web.model.pojo;

// Generated 03-sep-2013 1:05:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HistoriaVis generated by hbm2java
 */
public class HistoriaVis implements java.io.Serializable {

	private Long idhistoriavis;
	private Date timestamp;
	private Visita visita;
	private Incidencia incidencia;
	private EstadoVis estadoVis;
	private String descripcion;
	private Integer userid;

	public HistoriaVis() {
	}

	public HistoriaVis(Long idhistoriavis) {
		this.idhistoriavis = idhistoriavis;
	}

	public HistoriaVis(Long idhistoriavis, Visita visita,
			Incidencia incidencia, EstadoVis estadoVis, String descripcion,
			Integer userid) {
		this.idhistoriavis = idhistoriavis;
		this.visita = visita;
		this.incidencia = incidencia;
		this.estadoVis = estadoVis;
		this.descripcion = descripcion;
		this.userid = userid;
	}

	public Long getIdhistoriavis() {
		return this.idhistoriavis;
	}

	public void setIdhistoriavis(Long idhistoriavis) {
		this.idhistoriavis = idhistoriavis;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Visita getVisita() {
		return this.visita;
	}

	public void setVisita(Visita visita) {
		this.visita = visita;
	}

	public Incidencia getIncidencia() {
		return this.incidencia;
	}

	public void setIncidencia(Incidencia incidencia) {
		this.incidencia = incidencia;
	}

	public EstadoVis getEstadoVis() {
		return this.estadoVis;
	}

	public void setEstadoVis(EstadoVis estadoVis) {
		this.estadoVis = estadoVis;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

}
