package com.sigepro.web.model.pojo;

// Generated 03-sep-2013 1:05:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HistoriaCli generated by hbm2java
 */
public class HistoriaCli implements java.io.Serializable {

	private Long idhistoriacli;
	private Date timestamp;
	private EstadoCli estadoCli;
	private Cliente cliente;
	private String descripcion;
	private Integer userid;

	public HistoriaCli() {
	}

	public HistoriaCli(Long idhistoriacli) {
		this.idhistoriacli = idhistoriacli;
	}

	public HistoriaCli(Long idhistoriacli, EstadoCli estadoCli,
			Cliente cliente, String descripcion, Integer userid) {
		this.idhistoriacli = idhistoriacli;
		this.estadoCli = estadoCli;
		this.cliente = cliente;
		this.descripcion = descripcion;
		this.userid = userid;
	}

	public Long getIdhistoriacli() {
		return this.idhistoriacli;
	}

	public void setIdhistoriacli(Long idhistoriacli) {
		this.idhistoriacli = idhistoriacli;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public EstadoCli getEstadoCli() {
		return this.estadoCli;
	}

	public void setEstadoCli(EstadoCli estadoCli) {
		this.estadoCli = estadoCli;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

}
