package com.sigepro.web.model.pojo;

// Generated 03-sep-2013 1:05:44 by Hibernate Tools 3.4.0.CR1

/**
 * HistoriaIncId generated by hbm2java
 */
public class HistoriaIncId implements java.io.Serializable {

	private int idcliente;
	private long idincidencia;

	public HistoriaIncId() {
	}

	public HistoriaIncId(int idcliente, long idincidencia) {
		this.idcliente = idcliente;
		this.idincidencia = idincidencia;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public long getIdincidencia() {
		return this.idincidencia;
	}

	public void setIdincidencia(long idincidencia) {
		this.idincidencia = idincidencia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoriaIncId))
			return false;
		HistoriaIncId castOther = (HistoriaIncId) other;

		return (this.getIdcliente() == castOther.getIdcliente())
				&& (this.getIdincidencia() == castOther.getIdincidencia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcliente();
		result = 37 * result + (int) this.getIdincidencia();
		return result;
	}

}
