package com.sigepro.web.model.pojo;

// Generated 15-ago-2013 0:47:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Incidencia generated by hbm2java
 */
public class Incidencia implements java.io.Serializable {

	private Long idincidencia;
	private TipoInc tipoInc;
	private EstadoInc estadoInc;
	private Cliente cliente;
	private Date fechaInicio;
	private Date fechaCierre;
	private Date fechaUltMod;
	private String descripcion;
	private String titulo;
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<HistoriaInc> historiaIncs = new HashSet<HistoriaInc>(0);
	private Set<HistoriaVis> historiaVises = new HashSet<HistoriaVis>(0);

	public Incidencia() {
	}

	public Incidencia(Long idincidencia) {
		this.idincidencia = idincidencia;
	}

	public Incidencia(Long idincidencia, TipoInc tipoInc, EstadoInc estadoInc,
			Date fechaInicio, Date fechaCierre, Date fechaUltMod,
			 String descripcion) {
		this.idincidencia = idincidencia;
		this.tipoInc = tipoInc;
		this.estadoInc = estadoInc;
		this.fechaInicio = fechaInicio;
		this.fechaCierre = fechaCierre;
		this.fechaUltMod = fechaUltMod;
		this.descripcion = descripcion;
	}

	public Long getIdincidencia() {
		return this.idincidencia;
	}

	public void setIdincidencia(Long idincidencia) {
		this.idincidencia = idincidencia;
	}

	public TipoInc getTipoInc() {
		return this.tipoInc;
	}

	public void setTipoInc(TipoInc tipoInc) {
		this.tipoInc = tipoInc;
	}

	public EstadoInc getEstadoInc() {
		return this.estadoInc;
	}

	public void setEstadoInc(EstadoInc estadoInc) {
		this.estadoInc = estadoInc;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Date getFechaUltMod() {
		return this.fechaUltMod;
	}

	public void setFechaUltMod(Date fechaUltMod) {
		this.fechaUltMod = fechaUltMod;
	}


	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Visita> getVisitas() {
		return visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Set<HistoriaInc> getHistoriaIncs() {
		return historiaIncs;
	}

	public void setHistoriaIncs(Set<HistoriaInc> historiaIncs) {
		this.historiaIncs = historiaIncs;
	}

	public Set<HistoriaVis> getHistoriaVises() {
		return historiaVises;
	}

	public void setHistoriaVises(Set<HistoriaVis> historiaVises) {
		this.historiaVises = historiaVises;
	}
	
	

	
}
