package com.sigepro.web.model.pojo;

// Generated 15-ago-2013 0:47:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoInc generated by hbm2java
 */
public class TipoInc implements java.io.Serializable {

	private Integer idtipoincidencia;
	private String descripcion;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public TipoInc() {
	}

	public TipoInc(int idtipoincidencia) {
		this.idtipoincidencia = idtipoincidencia;
	}

	public TipoInc(int idtipoincidencia, String descripcion,
			Set<Incidencia> incidencias) {
		this.idtipoincidencia = idtipoincidencia;
		this.descripcion = descripcion;
		this.incidencias = incidencias;
	}

	public Integer getIdtipoincidencia() {
		return this.idtipoincidencia;
	}

	public void setIdtipoincidencia(Integer idtipoincidencia) {
		this.idtipoincidencia = idtipoincidencia;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Incidencia> getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}

}
